<?php
// Automatically generated by import-csv.php!
define('MM_TILEINFO', 
array (
  0 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'timer',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NES',
        'escalator' => '32',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '23',
        'properties' => 'yexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  1 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'timer',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      2 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'owarp',
      ),
      3 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      1 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '32',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
      1 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
      2 => 
      array (
        'walls' => 'NWS',
        'escalator' => '23',
        'properties' => 'gexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  2 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '20',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'ESW',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NWS',
        'escalator' => '01',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'pexit',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  3 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      2 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'timer',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'owarp',
      ),
      1 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  4 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'owarp',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'timer',
      ),
      2 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'WE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  5 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'ES',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      2 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'WS',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      1 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'timer',
      ),
      2 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'ES',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  6 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'yitem',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  7 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'WSE',
        'escalator' => '',
        'properties' => 'oitem',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'EW',
        'escalator' => '21',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
      1 => 
      array (
        'walls' => 'S',
        'escalator' => '13',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      3 => 
      array (
        'walls' => 'ESW',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
    ),
  ),
  8 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'gitem',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'ESW',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      3 => 
      array (
        'walls' => 'ES',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  9 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'WS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'owarp',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      3 => 
      array (
        'walls' => 'ESW',
        'escalator' => '',
        'properties' => 'pitem',
      ),
    ),
  ),
  10 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'SWN',
        'escalator' => '',
        'properties' => 'gexit',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '22',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => 'owarp',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NW',
        'escalator' => '11',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  11 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      2 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'yexit',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  12 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'oexit',
      ),
      1 => 
      array (
        'walls' => 'EWN',
        'escalator' => '10',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'WS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'WSN',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '01',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NES',
        'escalator' => '31',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'ENS',
        'escalator' => '',
        'properties' => 'owarp',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'WSE',
        'escalator' => '22',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  13 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'ES',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      2 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'Ns',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'nEW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
      2 => 
      array (
        'walls' => 'SN',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  14 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'We',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NwS',
        'escalator' => '20',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '12',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  15 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'crystal',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NWs',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'nE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'N',
        'escalator' => '30',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '22',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  16 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'ESW',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'EWs',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'Wn',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'camera',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'WN',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  17 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
      1 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'camera',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEW',
        'escalator' => '',
        'properties' => 'crystal',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  18 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NWE',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'camera',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  19 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'camera',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'WS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'WS',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      1 => 
      array (
        'walls' => 'SN',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NeS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'w',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      3 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
    ),
  ),
  20 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NE',
        'escalator' => '21',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SW',
        'escalator' => '12',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      3 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'crystal',
      ),
    ),
  ),
  21 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      2 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NSe',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      3 => 
      array (
        'walls' => 'SEw',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  22 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'ES',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  23 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'E',
        'escalator' => '',
        'properties' => 'oexplore',
      ),
      2 => 
      array (
        'walls' => 'SEW',
        'escalator' => '',
        'properties' => 'gwarp',
      ),
      3 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'SW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NW',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'S',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NES',
        'escalator' => '',
        'properties' => 'ywarp',
      ),
      1 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'pexplore',
      ),
      3 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
  24 => 
  array (
    0 => 
    array (
      0 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'NS',
        'escalator' => '',
        'properties' => 'yexplore',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NSW',
        'escalator' => '',
        'properties' => 'owarp',
      ),
    ),
    1 => 
    array (
      0 => 
      array (
        'walls' => 'NWS',
        'escalator' => '',
        'properties' => 'pwarp',
      ),
      1 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => '',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    2 => 
    array (
      0 => 
      array (
        'walls' => 'N',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'SE',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'NEWS',
        'escalator' => '',
        'properties' => '',
      ),
      3 => 
      array (
        'walls' => 'NeS',
        'escalator' => '',
        'properties' => '',
      ),
    ),
    3 => 
    array (
      0 => 
      array (
        'walls' => 'NE',
        'escalator' => '',
        'properties' => '',
      ),
      1 => 
      array (
        'walls' => 'EW',
        'escalator' => '',
        'properties' => '',
      ),
      2 => 
      array (
        'walls' => 'W',
        'escalator' => '',
        'properties' => 'gexplore',
      ),
      3 => 
      array (
        'walls' => 'SwE',
        'escalator' => '',
        'properties' => '',
      ),
    ),
  ),
));
