<?php
  echo "<?php\n";
?>
// Automatically generated by import-csv.php!
define('MM_TILEINFO', 
<?php
        $tileinfo = array();

        $handle = fopen(dirname(__FILE__) . '/modules/mm-tiles.csv', 'r');

        $firstrow = 1;
        while (($data = fgetcsv($handle)) !== false) {
            if ($firstrow) {
                $firstrow = 0;

                continue;
            }
            $num = count($data);
            // tile_id, cell, walls, escalator, properties
            $tile_id = $data[0];
            $cellx = intval($data[1][0]);
            $celly = intval($data[1][1]);
            $res = array(
                'walls' => $data[2],
                'escalator' => $data[3],
                'properties' => $data[4],
            );
            $tileinfo[$tile_id][$cellx][$celly] = $res;
        }
        fclose($handle);
        var_export($tileinfo); 

?>);
